["56,35"]
next = "+house6"
coordX = "28"
coordY = "27"

["47,35"]
next = "+house6"
coordX = "28"
coordY = "27"

["66,35"]
next = "+house6"
coordX = "28"
coordY = "27"

["71,25"]
next = "+house6"
coordX = "28"
coordY = "27"

["64,25"]
next = "+house6"
coordX = "28"
coordY = "27"

["48,25"]
next = "+house6"
coordX = "28"
coordY = "27"

["42,25"]
next = "+house6"
coordX = "28"
coordY = "27"

["55,15"]
next = "-route1"
coordX = "39"
coordY = "62"

["56,15"]
next = "-route1"
coordX = "40"
coordY = "62"

["57,15"]
next = "-route1"
coordX = "41"
coordY = "62"

["58,15"]
next = "-route1"
coordX = "42"
coordY = "62"

[[npc]]
cordsX = 63
cordsY = 38
character = [0,5,8,0,2,2,5,0]
hasQuestion = true
questionNum = 1
direction = 0

[[npc]]
cordsX = 44
cordsY = 34
character = [3,5,7,2,2,2,2,3]
hasQuestion = false
questionNum = 1
direction = 2

[[npc]]
cordsX = 42
cordsY = 46
character = [0,6,11,2,9,4,6,0]
hasQuestion = false
questionNum = 2
direction = 1

[[npc]]
cordsX = 62
cordsY = 43
character = [1,5,10,3,4,2,3,1]
hasQuestion = false
questionNum = 2
direction = 0

[[npc]]
cordsX = 40
cordsY = 25
character = [0,0,7,3,13,2,8,0]
hasQuestion = false
questionNum = 1
direction = 2