["56,35"]
next = "+room1"
coordX = "28"
coordY = "27"

["47,35"]
next = "+room1"
coordX = "28"
coordY = "27"

["66,35"]
next = "+room1"
coordX = "28"
coordY = "27"

["71,25"]
next = "+room1"
coordX = "28"
coordY = "27"

["64,25"]
next = "+room1"
coordX = "28"
coordY = "27"

["48,25"]
next = "+room1"
coordX = "28"
coordY = "27"

["42,25"]
next = "+room1"
coordX = "28"
coordY = "27"

["55,15"]
next = "+room1"
coordX = "28"
coordY = "27"

["56,15"]
next = "+room1"
coordX = "28"
coordY = "27"

["57,15"]
next = "+room1"
coordX = "28"
coordY = "27"

["58,15"]
next = "+room1"
coordX = "28"
coordY = "27"