["56,35"]
next = "+house6"
coordX = "28"
coordY = "27"

["47,35"]
next = "+house6"
coordX = "28"
coordY = "27"

["66,35"]
next = "+house6"
coordX = "28"
coordY = "27"

["71,25"]
next = "+house6"
coordX = "28"
coordY = "27"

["64,25"]
next = "+house6"
coordX = "28"
coordY = "27"

["48,25"]
next = "+house6"
coordX = "28"
coordY = "27"

["42,25"]
next = "+house6"
coordX = "28"
coordY = "27"

["55,15"]
next = "+house6"
coordX = "28"
coordY = "27"

["56,15"]
next = "+house6"
coordX = "28"
coordY = "27"

["57,15"]
next = "+house6"
coordX = "28"
coordY = "27"

["58,15"]
next = "+house6"
coordX = "28"
coordY = "27"

[[npc]]
cordsX = 58
cordsY = 38
character = [0,5,8,0,2,2,5,0]
hasQuestion = true
questionNum = "1"