["37,62"]
next = "-town1"
coordX = "57"
coordY = "17"

["38,62"]
next = "-town1"
coordX = "57"
coordY = "17"

["39,62"]
next = "-town1"
coordX = "57"
coordY = "17"

["40,62"]
next = "-town1"
coordX = "57"
coordY = "17"

["41,62"]
next = "-town1"
coordX = "57"
coordY = "17"

["42,62"]
next = "-town1"
coordX = "57"
coordY = "17"

["43,62"]
next = "-town1"
coordX = "57"
coordY = "17"
